FISH-5828 Connection Pool HealthCheck Exposed as MicroProfile Metrics
payara/Payara-Documentation pull request #107
Opened 2022-10-10 07:03 UTC by jGauravGupta

2022-10-10 08:57 UTC, AlanRoth approved these changes

2022-10-10 08:57 UTC, AlanRoth commented on docs/modules/ROOT/pages/Technical Documentation/MicroProfile/Metrics/Vendor Metrics.adoc
Can you include some text in-between headings; for [reference](https://payara.atlassian.net/wiki/spaces/SUP/pages/2149515318/Payara+Documentation+Style+Guide#Headings).

2022-10-10 09:35 UTC, JamesHillyard approved these changes
The level 5 headers are smaller than normal text which looks strange, but not a blocker.

2022-10-12 08:49 UTC, JamesHillyard requested changes
As this is an enterprise only feature - it should be moved to the enterprise section of the docs

2022-10-12 08:50 UTC, JamesHillyard commented
This is also Payara 5 Enterprise exclusive so should point to the `master` branch instead of `payara6-master`

2022-10-12 10:46 UTC, JamesHillyard approved these changes
Feature was changed to be Enterprise & Community & Payara 6 - Looks good!

2022-10-24 11:03 UTC, merged