FISH-872 Payara6 Ecosystem Documentation
payara/Payara-Documentation pull request #140
Opened 2022-10-31 10:15 UTC by JamesHillyard

Ports the Ecosystem IDE Improvements (SERV-817) to Payara 6 - Payara 6 with the ecosystem was tested and there are a few incompatibilities which have been documented / noted and had documentation removed.

2022-11-15 22:51 UTC, fturizo requested changes
Looks good, but requires some changes.

2022-11-15 22:51 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/Eclipse Plugin/Building Eclipse Plugin.adoc
> +This build job will create a both a zip and exploded format. The zip format of this build can be found in the  `[project_root]/build/packages` directory, and the exploded format can be found in the `
Might be better to reword the term as "exploded directory"-format.

2022-11-15 22:51 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/Eclipse Plugin/Overview.adoc
> +4. Read and accept the license.
"license agreement" (a bit nitpicky, but necessary)

2022-11-15 22:51 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/Eclipse Plugin/Payara Server.adoc
> +- Auto Publish & Hot Deploy your application
Would be good to put these elements in a formatted list.

2022-11-15 22:51 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/Hot Deploy and Auto Deploy.adoc
> +All four of the IDE Integrations supported by Payara allow for the use of Hot Deploy and Auto Deploy. After enabling either the Hot Deploy or Auto Deploy feature on your IDE of choice, simply deploy
"Payara Server"

2022-11-15 22:51 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Building IntelliJ Plugin.adoc
> +Gradle is the build tool for the Payara Tools IntelliJ IDEA plugin. You can either download and configure Gradle locally or use the Gradle wrapper in the sourcecode.
typo: source code

2022-11-15 22:51 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Payara Micro.adoc
> +=== Debugging the Payara Micro Application
This section is missing an id for an anchor link

2022-11-15 22:51 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/VSCode Extension/Payara Server.adoc
> +== Magaging Applications on Payara Server
Typo: Managing

2022-11-15 22:51 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/VSCode Extension/Building VSCode Extension.adoc
> +The Payara Tools VS Code IDE Extension sourcecode is available in the https://github.com/payara/ecosystem-vscode-plugin[VS Code Extension repository].
typo: source code

2022-11-15 22:51 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/VSCode Extension/Building VSCode Extension.adoc
> +You must first clone the repository where the extension sourcecode is stored. https://github.com/payara/ecosystem-vscode-plugin[VS Code Extension repository]
typo: source code

2022-11-15 22:51 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Overview.adoc
> +IMPORTANT: Currently there is no support for Payara 6 with the NetBeans IDE.
small grammar fix: within

2022-11-15 22:51 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Building NetBeans Plugin.adoc
> +As Apache NetBeans IDE provides out-of-the-box support for Payara Platform, the sourcecode for the NetBeans IDE Plugin is contained within the https://github.com/apache/netbeans[NetBeans Code Reposit
typo: source code

2022-11-15 22:51 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Building NetBeans Plugin.adoc
> +Apache Ant is the build tool for the Payara Tools Eclipse IDE Plugin and must be configured locally. https://ant.apache.org/manual/install.html[Install Apache Ant]
This sentence mentions Eclipse IDE instead of Netbeans.

2022-11-22 16:15 UTC, JamesHillyard commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/Hot Deploy and Auto Deploy.adoc
> +All four of the IDE Integrations supported by Payara allow for the use of Hot Deploy and Auto Deploy. After enabling either the Hot Deploy or Auto Deploy feature on your IDE of choice, simply deploy
This applies to both Server and Micro, but the IDE Plugins are maintained by us, Payara, hence I went with 
> All four of the IDE Integrations supported by Payara
Do you think this should be worded differently?

2022-11-28 22:26 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/Hot Deploy and Auto Deploy.adoc
> +All four of the IDE Integrations supported by Payara allow for the use of Hot Deploy and Auto Deploy. After enabling either the Hot Deploy or Auto Deploy feature on your IDE of choice, simply deploy
In that case use "Payara Platform", since this keeps the distinction between product and company

2022-11-29 12:37 UTC, JamesHillyard commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/Hot Deploy and Auto Deploy.adoc
> +All four of the IDE Integrations supported by Payara allow for the use of Hot Deploy and Auto Deploy. After enabling either the Hot Deploy or Auto Deploy feature on your IDE of choice, simply deploy
Removed the whole sentence as this isn't actually true, IntelliJ has no Hot Deploy / Auto Deploy support

2022-11-29 12:37 UTC, JamesHillyard commented
Can't re-request but @fturizo to review again please

2022-11-29 16:55 UTC, fturizo approved these changes
All good can proceed to merge the docs.

2022-11-30 09:12 UTC, merged