FISH-6643: adding versioning for Amazon SQS
payara/Payara-Documentation pull request #159
Opened 2022-11-23 01:44 UTC by breakponchito

2022-11-25 19:26 UTC, fturizo requested changes
Looks good, some changes needed.

2022-11-25 19:26 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS Versioning.adoc
> +This is the first version of the connector that is based on https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/welcome.html[Amazon SDK 1]. To view how to use, please check the following link
"To  view how to use" is a bit obtuse. Better state "Please check [link] for more information about how the connector works".

2022-11-25 19:26 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS Versioning.adoc
> +This is the second version of the connector that is based on https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/home.html[Amazon SDK 2]. This version is based on a major rewrite of the v
Is there any special detail on the connector being built on top of JDK 8? Or is this a typo?

2022-11-25 19:26 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS Versioning.adoc
> +
Header missing an ID.

2022-11-25 19:26 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS Versioning.adoc
> +* Amazon SQS - ./AmazonSQS/AmazonSQSRAR/target/amazon-sqs-rar-0.9.0-SNAPSHOT.rar
Better to put this path on a dedicated formatted block for better readability

2022-11-25 19:26 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS Versioning.adoc
> +Note that these dependencies have scope provided since the types within this dependency are globally available to every application deployed to Payara Micro after the `amazon-sqs-rar-0.9.0-SNAPSHOT.r
This paragraph would look better in a NOTE admonition.

2022-12-01 01:08 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS Versioning.adoc
> +This is the first version of the connector that is based on https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/welcome.html[Amazon SDK 1]. To view how to use, please check the following link
already removed, not needed

2022-12-01 01:09 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS Versioning.adoc
> +This is the second version of the connector that is based on https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/home.html[Amazon SDK 2]. This version is based on a major rewrite of the v
removed not needed

2022-12-01 01:09 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS Versioning.adoc
> +* Amazon SQS - ./AmazonSQS/AmazonSQSRAR/target/amazon-sqs-rar-0.9.0-SNAPSHOT.rar
already updated

2022-12-01 01:10 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS Versioning.adoc
> +Note that these dependencies have scope provided since the types within this dependency are globally available to every application deployed to Payara Micro after the `amazon-sqs-rar-0.9.0-SNAPSHOT.r
already moved to a note

2022-12-01 01:11 UTC, breakponchito commented
Still not merge until the versioning is resolved

2022-12-13 20:00 UTC, fturizo requested changes
On top of the comments in the files, some additional changes  are needed:

* Remove any personal information from the images listed.
* Obscure explicit Amazon object IDs 
* Replace Amazon images with text in Spanish to equivalent images using English UI

2022-12-13 20:00 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS Versioning.adoc
> +This is the first version of the connector that is based on https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/welcome.html[Amazon SDK 1]. To view how to use, please check xref:/Technical Do
It is better to state: "Please check <link> for more information about how the connector works"

2022-12-13 20:00 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS Versioning.adoc
> +This is the second version of the connector that is based on https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/home.html[Amazon SDK 2]. To view how to use, please go to the next section
Remove the second sentence as the information is present in the next section.

2022-12-13 20:00 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS Versioning.adoc
> +The connector can be found in the following location as JCA rar:
`rar` should be in uppercase

2022-12-13 20:00 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS Versioning.adoc
> +NOTE: These dependencies have scope provided since the types within this dependency are globally available to every application deployed to Payara Micro after the `amazon-sqs-rar-1.0.0.rar` was deplo
No need to explain why the dependencies have provided scope. Just a simple "These dependencies are already part of the Payara Platform distributions" is enough.

2022-12-13 20:00 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS with Amazon SSO.adoc
> +This kind of accounts can be used to consume SQS queues from Payara. To configure this you must need to follow the next steps:
Better to re-state this sentence as; "AWS Accounts can be used to configure SQS queues to be consumed by applications deployed in the Payara Platform"

2022-12-13 20:00 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS with Amazon SSO.adoc
> +On our example the base directory was created and you can check on the settings section:
In this sentence (and other occurrences that follow), it is better to say "In this example ..." rather than "our example" as this makes the statement impersonal.

2022-12-13 20:00 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS with Amazon SSO.adoc
> +[source,text]
The source for this code fragment should be `shell` instead of text

2022-12-13 20:00 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS with Amazon SSO.adoc
> +NOTE: The sso_start_url, sso_region and sso_role_name are associated with the sso credential you created previously, and to get the sso_account_id please check https://docs.aws.amazon.com/IAM/latest/
The sso parameter names should be in `monospaced` format

2022-12-13 20:00 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS with Amazon SSO.adoc
> +Then it is needed to do the SSO login from the CLI command line:
Say: "Next, execute the SSO login from the CLI" instead

2022-12-13 20:00 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS with Amazon SSO.adoc
> +[source,text]
The sso parameter names should be in `monospaced` format

2022-12-13 20:00 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS with Amazon SSO.adoc
> +----
This should be shell code block

2022-12-13 20:00 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS with Amazon SSO.adoc
> +>java -jar "path for payara micro jar"\payara-micro.jar --deploy "path for amazon sqs rar"\amazon-sqs-rar-1.0.0.rar "path for example"\amazon-sqs-example-1.0.0.jar
Remove the "path for payara micro jar" and "path for amazon sqs rar" elements in this command, as they are not needed. Users should be aware of where these artefacts are.

2022-12-13 20:00 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS with Amazon SSO.adoc
> +NOTE: This kind of accounts are used just on development environments and not recommended to production environment.
This statement should be in an IMPORTANT admonition. Also, it is better to phrase it as "Using AWS SSO credentials is a  recommended practice for development environments only. Please refrain from using this setup on production environments".

2022-12-15 04:39 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS Versioning.adoc
> +This is the first version of the connector that is based on https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/welcome.html[Amazon SDK 1]. To view how to use, please check xref:/Technical Do
already done

2022-12-15 04:39 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS Versioning.adoc
> +This is the second version of the connector that is based on https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/home.html[Amazon SDK 2]. To view how to use, please go to the next section
already done

2022-12-15 04:39 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS Versioning.adoc
> +The connector can be found in the following location as JCA rar:
already done

2022-12-15 04:39 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS Versioning.adoc
> +NOTE: These dependencies have scope provided since the types within this dependency are globally available to every application deployed to Payara Micro after the `amazon-sqs-rar-1.0.0.rar` was deplo
already done

2022-12-15 04:39 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS with Amazon SSO.adoc
> +This kind of accounts can be used to consume SQS queues from Payara. To configure this you must need to follow the next steps:
already done

2022-12-15 04:39 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS with Amazon SSO.adoc
> +Then it is needed to do the SSO login from the CLI command line:
already done

2022-12-15 04:40 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS with Amazon SSO.adoc
> +[source,text]
already done

2022-12-15 04:40 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS with Amazon SSO.adoc
> +----
already done

2022-12-15 04:40 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS with Amazon SSO.adoc
> +>java -jar "path for payara micro jar"\payara-micro.jar --deploy "path for amazon sqs rar"\amazon-sqs-rar-1.0.0.rar "path for example"\amazon-sqs-example-1.0.0.jar
already done

2022-12-15 04:40 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS with Amazon SSO.adoc
> +NOTE: This kind of accounts are used just on development environments and not recommended to production environment.
already done

2022-12-16 21:28 UTC, fturizo approved these changes
Re-structured the PR with Alfonso's help to clarify versioning and other details. Should be good to go.

2022-12-19 21:45 UTC, merged

2022-12-22 23:01 UTC, fturizo commented
@breakponchito, are these features also coming to Payara 6? If so, this PR needs to be replicated in the `payara6-master` branch as well. Please check ASAP.