FISH-6475 : new feature to migrate projects and files
payara/Payara-Documentation pull request #168
Opened 2022-12-10 14:58 UTC by luiseufrasio

2023-01-13 22:29 UTC, fturizo requested changes
Looks good, however, as in with the recent VSCode Jakarta EE "conversion" feature was documented with inconsistent terminology (migrate, migration, etc.), it was decided that the term to use to refer to the feature was "transform".

To keep the feature's documentation consistent across ALL ecosystem tools, please rename all occurrences of the words "migrate/migration", "refactor/refactoring" and similar to the word "transform/transformation". Please do this in both text and images to make sure that there is no confusion on the user's part.

2023-01-13 22:29 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +Using the `Payara Platform Tools` and `Payara Micro Community Tools` plugins, you can migrate whole projects or just a file from JavaEE to Jakarta-EE-10.
For consistency, "JavaEE" should be "Java EE 8" and "Jakarta-EE-10" should be "Jakarta EE 10". Please make sure to fix similar instances through this page.

2023-01-13 22:29 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +NOTE: This is available in both plugins, therefore you need to install one of them to use this feature.
For better readability it is best to state: "This feature is available in both Community and Enterprise versions of the plugin"

2023-01-13 22:29 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +IMPORTANT: To see the project being created open IntelliJ Console.
Weird sentence, maybe it should be better to say: "You can see the output of the generation process in the IntelliJ console"

2023-01-13 22:29 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +The `maven` command that do the transformation process is runned into IntelliJ Console:
Maven should be capitalized and it shouldn't be in a monospaced format. Also tthis sentence is a bit weird as well. It should say: "The output of the Maven plugin that executes the code transformation can be reviewed in the IDE's console"

2023-01-13 22:29 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +After the creation, a maven `BUILD SUCCESS` message should be logged on Console.
maven --> Maven
"'should be logged in the IDE's console"

2023-01-13 22:29 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +== Refactor a JavaEE File to Jakarta-EE-10
This title should be read as "Transform a single file" since the Java/Jakarta EE details are already inferred.

2023-01-13 22:29 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +The `maven` command that do the transformation process is runned into IntelliJ Console:
"The Maven plugin that executes the transformation process will print its output to the IDE's console"

2023-01-13 22:29 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +IMPORTANT: To see the file being created open IntelliJ Console.
Same comment as the one in the same note above.

2023-01-13 22:29 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +The new file can be viewed into the destination package chosen.
"The new file will be located in the chosen destination packaged for its review"

2023-01-13 22:29 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +After the file creation, a maven `BUILD SUCCESS` message is logged on Console.
After the new file is created, a `BUILD SUCCESS` message from the Maven plugin will be logged in the IDE's console.

2023-01-13 22:29 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +NOTE: When the whole project is migrated, the plugin adds `JakartaEE10` at the end of the project name. In our example, `demo-JakartaEE10` project was created from `demo` project. In case of a file m
`jakartaee10` should be in monospaced format. Also, the last sentences should say "a `jakartaee10` package will be created in the destination package"

2023-01-14 11:05 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +Using the `Payara Platform Tools` and `Payara Micro Community Tools` plugins, you can migrate whole projects or just a file from JavaEE to Jakarta-EE-10.
done

2023-01-14 11:05 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +NOTE: This is available in both plugins, therefore you need to install one of them to use this feature.
done

2023-01-14 11:06 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +IMPORTANT: To see the project being created open IntelliJ Console.
done

2023-01-14 11:07 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +After the creation, a maven `BUILD SUCCESS` message should be logged on Console.
done

2023-01-14 11:08 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +== Refactor a JavaEE File to Jakarta-EE-10
done

2023-01-14 11:10 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +The `maven` command that do the transformation process is runned into IntelliJ Console:
done

2023-01-14 11:28 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +IMPORTANT: To see the file being created open IntelliJ Console.
done

2023-01-14 11:29 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +After the file creation, a maven `BUILD SUCCESS` message is logged on Console.
done

2023-01-14 11:30 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +The `maven` command that do the transformation process is runned into IntelliJ Console:
done

2023-01-14 11:33 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +The new file can be viewed into the destination package chosen.
done, I just removed "for its review".

2023-01-14 11:35 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +NOTE: When the whole project is migrated, the plugin adds `JakartaEE10` at the end of the project name. In our example, `demo-JakartaEE10` project was created from `demo` project. In case of a file m
done

2023-01-17 10:47 UTC, JamesHillyard commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +The `New Project` is opened on a new window.
If I understand correctly this will make a new project with the suffix 'JakartaEE-10' right? If that's true then this sentence needs to explain what the 'New Project' will be called, where will I find it? etc

2023-01-17 10:47 UTC, JamesHillyard commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +NOTE: When the whole project is migrated, the plugin adds `jakartaEE10` at the end of the project name. In our example, `demo-JakartaEE10` project was created from `demo` project. In case of a file m
I would split this up into two notes, one under transform a project and one here under transform a file with the relevant details. This will also address my other comment

2023-01-17 10:47 UTC, JamesHillyard commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> += Migrate Maven Projects or Files From Java EE 8 to Jakarta EE 10
As @fturizo said this should be 'Transform Maven Projects....' although in IntelliJ the feature specifically says migrate, should the feature say 'Transform to JakartaEE-10' instead to avoid confusion?

2023-04-02 11:57 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> += Migrate Maven Projects or Files From Java EE 8 to Jakarta EE 10
done

2023-04-02 11:57 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +NOTE: When the whole project is migrated, the plugin adds `jakartaEE10` at the end of the project name. In our example, `demo-JakartaEE10` project was created from `demo` project. In case of a file m
done

2023-04-02 11:58 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Migrate to Jakarta-EE10.adoc
> +The `New Project` is opened on a new window.
done

2023-04-20 11:51 UTC, JamesHillyard commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Transform to Jakarta-EE10.adoc
> +:ordinal: 1
```suggestion
```

2023-04-20 11:51 UTC, JamesHillyard commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Transform to Jakarta-EE10.adoc
> +== Transform a single file
```suggestion
== Transform a Single File
```

2023-04-20 11:53 UTC, JamesHillyard commented
In the interest of getting this moving again I'm happy for this to be merged as is, the content is fit for purpose. @fturizo It might be useful for someone in your team to go through the 'Migration to Jakarta EE 10' pages for all 4 IDEs (They have all been finished now) and make them fully consistent with eachother

2023-04-20 11:54 UTC, JamesHillyard approved these changes
Approved - See comment above

2023-08-15 17:03 UTC, merged