FISH-6436 : keystores change documentation
payara/Payara-Documentation pull request #188
Opened 2023-01-11 18:26 UTC by luiseufrasio

2023-01-13 09:53 UTC, JamesHillyard requested changes

2023-01-13 09:53 UTC, JamesHillyard commented on community/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Configuration Options/SSL Certificates.adoc
> +IMPORTANT: From Payara version 6 the keystores were migrated from JKS to PKCS12 format.
This isn't strictly true as 6.2022.1, 6.2022.2 and 6.2023.1 use JKS, should instead say 6.2023.2 and later

2023-01-13 09:53 UTC, JamesHillyard commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Configuration Options/SSL Certificates.adoc
> +IMPORTANT: From Payara version 6 the keystores were migrated from JKS to PKCS12 format.
See other comment

2023-01-14 12:00 UTC, luiseufrasio commented on community/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Configuration Options/SSL Certificates.adoc
> +IMPORTANT: From Payara version 6 the keystores were migrated from JKS to PKCS12 format.
done

2023-01-14 12:01 UTC, luiseufrasio commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Configuration Options/SSL Certificates.adoc
> +IMPORTANT: From Payara version 6 the keystores were migrated from JKS to PKCS12 format.
done

2023-01-14 20:27 UTC, JamesHillyard approved these changes
Looks good, please don't merge this until documentation cuts have been taken for the current release which doesn't include this change

2023-01-19 10:13 UTC, merged