FISH-5722 document concurrency config in payara-resources.xml
payara/Payara-Documentation pull request #21
Opened 2022-06-27 17:53 UTC by aubi

2022-06-28 08:09 UTC, Pandrex247 requested changes

2022-06-28 08:09 UTC, Pandrex247 commented on enterprise/docs/antora.yml
> +    payaraResourcesDtd: 'https://raw.githubusercontent.com/payara/Payara-Documentation/master/docs/modules/ROOT/pages/Appendix/Schemas/payara-resources_1_6.dtd'
Should this now not be 1_7?

2022-06-28 08:54 UTC, Pandrex247 commented on enterprise/docs/antora.yml
> +    payaraResourcesDtd: 'https://raw.githubusercontent.com/payara/Payara-Documentation/master/docs/modules/ROOT/pages/Appendix/Schemas/payara-resources_1_6.dtd'
it's being added in this PR

2022-06-28 14:43 UTC, Pandrex247 commented on enterprise/docs/antora.yml
> +    payaraResourcesDtd: 'https://raw.githubusercontent.com/payara/Payara-Documentation/master/docs/modules/ROOT/pages/Appendix/Schemas/payara-resources_1_6.dtd'
```suggestion
    payaraResourcesDtd: 'https://raw.githubusercontent.com/payara/Payara-Documentation/master/docs/modules/ROOT/pages/Appendix/Schemas/payara-resources_1_7.dtd'
```

2022-06-29 11:53 UTC, aubi commented on enterprise/docs/antora.yml
> +    payaraResourcesDtd: 'https://raw.githubusercontent.com/payara/Payara-Documentation/master/docs/modules/ROOT/pages/Appendix/Schemas/payara-resources_1_6.dtd'
Copy&paste error :-)

2022-06-29 11:57 UTC, aubi commented
@fturizo Fabio, it is a good idea. I was thinking about it -- it will need to show, how to use ManagedExecutorService, ManagedScheduledExecutorService and ManagedThreadFactory first. Then how to define them in GUI and then how to do the same in payara-resources.xml.
Let's do a Jira ticket for it. It's a bit more work.

2022-06-29 14:15 UTC, Pandrex247 approved these changes

2022-06-29 14:17 UTC, Pandrex247 commented
Documentation will also need republishing once this is merged, this is for the release which went out today and I believe the 5.40.0 docs have been published

2022-06-29 15:50 UTC, AlanRoth commented
> Documentation will also need republishing once this is merged, this is for the release which went out today and I believe the 5.40.0 docs have been published

I'll sort it

2022-06-29 15:50 UTC, merged