FISH-6976: upgrading metrics documentacion to 5
payara/Payara-Documentation pull request #213
Opened 2023-03-06 14:54 UTC by breakponchito

Upgrading documentation for metrics 5

2023-03-07 15:09 UTC, JamesHillyard requested changes

2023-03-07 15:09 UTC, JamesHillyard commented on docs/modules/ROOT/pages/Technical Documentation/MicroProfile/Metrics/Metrics Rest Endpoint.adoc
> +These metrics must tag with `mp_scope=scope_name`.
These +'s are being shown as actual + rather than for formatting, I'd move this section above the example so it's formatted consistently and correctly
![image](https://user-images.githubusercontent.com/73830120/223462759-7af68c7d-e096-4560-8519-f9748e95b8a2.png)

2023-03-08 21:49 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/MicroProfile/Metrics/Metrics Rest Endpoint.adoc
> +The Metrics specification {mpMetricsSpecUrl}#scopes[defines three _Scopes_], **Base**, **Vendor**, **Application** and **Custom** which correspond to the following purposes:
already done, thanks

2023-03-08 22:02 UTC, JamesHillyard approved these changes

2023-03-09 20:02 UTC, fturizo requested changes
LGTM, just a set of minor grammar issues to fix.

2023-03-09 20:02 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/MicroProfile/Metrics/Metrics Rest Endpoint.adoc
> +These metrics must tag with `mp_scope=base`.
Minor grammar issue: "Must be tagged"

2023-03-09 20:02 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/MicroProfile/Metrics/Metrics Rest Endpoint.adoc
> +These metrics must tag with `mp_scope=vendor`.
Minor grammar issue: "Must be tagged"

2023-03-09 20:02 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/MicroProfile/Metrics/Metrics Rest Endpoint.adoc
> +These metrics must tag with `mp_scope=application`.
Minor grammar issue: "Must be tagged"

2023-03-09 20:02 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/MicroProfile/Metrics/Metrics Rest Endpoint.adoc
> +Applications may also define their own scope names by tagging metrics with another scope (other than base, vendor or application).
Better to state: "by tagging metrics with a custom scope name (other than base, vendor or application)."

2023-03-09 20:02 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/MicroProfile/Metrics/Metrics Rest Endpoint.adoc
> +These metrics must tag with `mp_scope=scope_name`.
Minor grammar issue: "Must be tagged"

2023-03-09 20:11 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/MicroProfile/Metrics/Metrics Rest Endpoint.adoc
> +These metrics must tag with `mp_scope=base`.
already done

2023-03-09 20:11 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/MicroProfile/Metrics/Metrics Rest Endpoint.adoc
> +These metrics must tag with `mp_scope=vendor`.
already done

2023-03-09 20:12 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/MicroProfile/Metrics/Metrics Rest Endpoint.adoc
> +Applications may also define their own scope names by tagging metrics with another scope (other than base, vendor or application).
already done

2023-03-09 20:12 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/MicroProfile/Metrics/Metrics Rest Endpoint.adoc
> +These metrics must tag with `mp_scope=scope_name`.
already done

2023-03-09 20:12 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/MicroProfile/Metrics/Metrics Rest Endpoint.adoc
> +These metrics must tag with `mp_scope=application`.
already done

2023-03-09 20:16 UTC, fturizo approved these changes
All good.

2023-03-09 20:16 UTC, merged