FISH-7168 SNMP4J Link
payara/Payara-Documentation pull request #219
Opened 2023-03-14 09:18 UTC by JamesHillyard

Update SNMP4J link to the payara compatible repackaged jar.

2023-03-14 12:50 UTC, Pandrex247 requested changes

2023-03-14 12:50 UTC, Pandrex247 commented on community/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Extensions/Notifiers/SNMP.adoc
> +- link:https://nexus.payara.fish/repository/payara-artifacts/org/snmp4j/snmp4j/3.7.5/snmp4j-3.7.5.jar[Dependency: SNMP4J 3.7.5]
I dislike republishing things as the same version when they aren't the same.
It should either be published as 3.7.5.payara-p1, or simply published at the original repackaged coordinates.

2023-03-14 12:50 UTC, Pandrex247 commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Logging and Monitoring/Notification Service/Notifiers/SNMP Notifier.adoc
> +- link:https://nexus.payara.fish/repository/payara-artifacts/org/snmp4j/snmp4j/3.7.5/snmp4j-3.7.5.jar[Dependency: SNMP4J 3.7.5]
I dislike republishing things as the same version when they aren't the same.
It should either be published as 3.7.5.payara-p1, or simply published at the original repackaged coordinates.

2023-03-15 09:43 UTC, JamesHillyard commented on community/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Extensions/Notifiers/SNMP.adoc
> +- link:https://nexus.payara.fish/repository/payara-artifacts/org/snmp4j/snmp4j/3.7.5/snmp4j-3.7.5.jar[Dependency: SNMP4J 3.7.5]
Republished at the original repackaged coordinates, deleted the old upload from Nexus and the link has been updated.

2023-03-15 09:43 UTC, JamesHillyard commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Logging and Monitoring/Notification Service/Notifiers/SNMP Notifier.adoc
> +- link:https://nexus.payara.fish/repository/payara-artifacts/org/snmp4j/snmp4j/3.7.5/snmp4j-3.7.5.jar[Dependency: SNMP4J 3.7.5]
Republished at the original repackaged coordinates, deleted the old upload from Nexus and the link has been updated.

2023-03-16 16:52 UTC, Pandrex247 approved these changes

2023-03-16 16:55 UTC, merged