6.2023.3 Jakarta TCK, MicroProfile TCK and Release Notes
payara/Payara-Documentation pull request #227
Opened 2023-03-28 12:31 UTC by JamesHillyard

Title

2023-03-28 16:52 UTC, Pandrex247 requested changes

2023-03-28 16:52 UTC, Pandrex247 commented on community/docs/modules/ROOT/pages/Eclipse MicroProfile Certification/6.2023.3/Server Full TCK Results.adoc
> +```
Since we lack an "additional certification requirements" space here, it's probably worth linking to our challenge.

2023-03-28 16:52 UTC, Pandrex247 commented on community/docs/modules/ROOT/pages/Eclipse MicroProfile Certification/6.2023.3/Server Web TCK Results.adoc
> +```
Since we lack an "additional certification requirements" space here, it's probably worth linking to our challenge.

2023-03-28 16:52 UTC, Pandrex247 commented on community/docs/modules/ROOT/pages/Eclipse MicroProfile Certification/6.2023.3/Server Web TCK Results.adoc
> +NOTE: A challenge has been raised against the OpenAPI 3.1 TCK here: https://github.com/eclipse/microprofile-open-api/issues/557. For the official TCK run with challenged tests excluded see "Unaltered
I'd point at the official PR, not our one.
```suggestion
NOTE: A challenge has been raised against the OpenAPI 3.1 TCK here: https://github.com/eclipse/microprofile-open-api/issues/557. For the official TCK run with challenged tests excluded see "Unaltered TCK", for the Payara Patched TCK see "Payara Patched TCK". The Payara patch to the TCK is here: https://github.com/eclipse/microprofile-open-api/pull/559
```

2023-03-28 16:52 UTC, Pandrex247 commented on community/docs/modules/ROOT/pages/Eclipse MicroProfile Certification/6.2023.3/Server Full TCK Results.adoc
> +NOTE: A challenge has been raised against the OpenAPI 3.1 TCK here: https://github.com/eclipse/microprofile-open-api/issues/557. For the official TCK run with challenged tests excluded see "Unaltered
I'd point at the official PR, not our one.
```suggestion
NOTE: A challenge has been raised against the OpenAPI 3.1 TCK here: https://github.com/eclipse/microprofile-open-api/issues/557. For the official TCK run with challenged tests excluded see "Unaltered TCK", for the Payara Patched TCK see "Payara Patched TCK". The Payara patch to the TCK is here: https://github.com/eclipse/microprofile-open-api/pull/559
```

2023-03-28 16:58 UTC, Pandrex247 commented on community/docs/modules/ROOT/pages/Release Notes/Release Notes 6.2023.3.adoc
Missing FISH-6907?

2023-03-29 08:18 UTC, JamesHillyard commented on community/docs/modules/ROOT/pages/Release Notes/Release Notes 6.2023.3.adoc
It's missing because it was marked as 'New Feature' not 'Improvement' - I've informed marketing and will update this PR and GitHub shortly

2023-03-29 09:48 UTC, Pandrex247 approved these changes

2023-03-29 11:31 UTC, merged