[master] Updated Clustered Singleton.adoc
payara/Payara-Documentation pull request #230
Opened 2023-03-28 16:14 UTC by felixif

I updated the information on the page, recommending users set the `serialVersionUID` to avoid possible issues at re-deployment.

2023-03-29 11:58 UTC, AlanRoth commented on docs/modules/ROOT/pages/Technical Documentation/Public API/Clustered Singleton.adoc
> +It is also highly recommended to add a `serialVersionUID` variable to the `@Clustered @Singleton` class, in order to remember versions of the `@Clustered @Singleton` class to verify that a loaded cla
Could be put in a IMPORTANT or TIP admonition, what do you think?

2023-03-29 12:55 UTC, felixif commented on docs/modules/ROOT/pages/Technical Documentation/Public API/Clustered Singleton.adoc
> +It is also highly recommended to add a `serialVersionUID` variable to the `@Clustered @Singleton` class, in order to remember versions of the `@Clustered @Singleton` class to verify that a loaded cla
Yep, I agree! I will update it now.

2023-03-29 19:54 UTC, fturizo requested changes
Couple of changes needed.

2023-03-29 19:54 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Public API/Clustered Singleton.adoc
> +It is also highly recommended to add a `serialVersionUID` variable to the `@Clustered @Singleton` class, in order to remember versions of the `@Clustered @Singleton` class to verify that a loaded cla
A bit redundant to say `@Clustered @Singleton` twice: Once is enough. Also, this paragraph should state:

"that a previous serialized entry in the Data Grid is compatible with updated versions of the same class".

2023-03-29 19:54 UTC, fturizo commented
@felixif, please don't forget to make an equivalent port of this PR to `payara6-master`.

2023-03-30 21:09 UTC, fturizo approved these changes

2023-03-30 21:09 UTC, merged