FISH-6980 add ear libs to openapi scan
payara/Payara-Documentation pull request #238
Opened 2023-04-12 15:40 UTC by aubi

Fix `mp.openapi.extensions.scan.lib` property name
Update scanning of jars in ear's `lib/` directory, change introduced in FISH-6980

2023-04-17 14:16 UTC, AlanRoth requested changes
Is #239 a duplicate of this?

2023-04-18 08:29 UTC, JamesHillyard commented
FISH-6980 isn't going into the current release. Do not merge until documentation cuts for the release have been taken

2023-04-18 13:41 UTC, Pandrex247 requested changes

2023-04-18 13:41 UTC, Pandrex247 commented on community/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc
> +| `mp.openapi.extensions.scan.lib`  |  Configuration property that allows the server to scan packaged JAR files inside the WAR's library directory (`WEB-INF/lib`). If the WAR is inside EAR, the serve
Wording
```suggestion
| `mp.openapi.extensions.scan.lib`  |  Configuration property that allows the server to scan packaged JAR files inside the WAR's library directory (`WEB-INF/lib`). If the WAR is inside EAR, the server also scans JAR files inside the EAR's `lib/` directory. Default value is `false`.
```

2023-04-18 14:54 UTC, closed without merging