Fish 6980 add ear libs to openapi scan ent
payara/Payara-Documentation pull request #239
Opened 2023-04-13 14:00 UTC by aubi

Fix `mp.openapi.extensions.scan.lib` property name
Update scanning of jars in ear's `lib/` directory, change introduced in FISH-6980

Merge after finishing Community change: https://github.com/payara/Payara-Documentation/pull/238

2023-04-18 08:30 UTC, JamesHillyard commented
FISH-6980 isn't going into the current release. Do not merge until documentation cuts for the release have been taken

2023-04-18 13:42 UTC, Pandrex247 requested changes

2023-04-18 13:42 UTC, Pandrex247 commented on community/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc
> +| `mp.openapi.extensions.scan.lib`  |  Configuration property that allows the server to scan packaged JAR files inside the WAR's library directory (`WEB-INF/lib`). If the WAR is inside EAR, the serve
Wording
```suggestion
| `mp.openapi.extensions.scan.lib`  |  Configuration property that allows the server to scan packaged JAR files inside the WAR's library directory (`WEB-INF/lib`). If the WAR is inside EAR, the server also scans JAR files inside the EAR's `lib/` directory. Default value is `false`.
```

2023-04-18 13:42 UTC, Pandrex247 commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc
> +When a `name` key is provided with a string value, the schema will be added to the `schemas` collection in the `components` object of the resulting OpenAPI document using `name`'s value as the key.
I don't think this renders correctly.
Looking at the preview it's wrong.

2023-04-18 13:42 UTC, Pandrex247 commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc
> +| `mp.openapi.extensions.scan.lib`  |  Configuration property that allows the server to scan packaged JAR files inside the WAR's library directory (`WEB-INF/lib`). If the WAR is inside EAR, the serve
Wording
```suggestion
| `mp.openapi.extensions.scan.lib`  |  Configuration property that allows the server to scan packaged JAR files inside the WAR's library directory (`WEB-INF/lib`). If the WAR is inside EAR, the server also scans JAR files inside the EAR's `lib/` directory. Default value is `false`.
```

2023-04-18 16:58 UTC, aubi commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc
> +When a `name` key is provided with a string value, the schema will be added to the `schemas` collection in the `components` object of the resulting OpenAPI document using `name`'s value as the key.
The old rendering is wrong in the old version in the same way.

2023-04-18 17:44 UTC, aubi commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc
> +When a `name` key is provided with a string value, the schema will be added to the `schemas` collection in the `components` object of the resulting OpenAPI document using `name`'s value as the key.
This one was tricky: https://docs.asciidoctor.org/asciidoc/latest/text/quotation-marks-and-apostrophes/#possessive-monospace

2023-04-19 08:12 UTC, Pandrex247 approved these changes

2023-04-19 13:24 UTC, merged