[master] [SERV-952] Added section for Codehaus Cargo plugin
payara/Payara-Documentation pull request #240
Opened 2023-04-13 15:37 UTC by felixif

Added a new section describing the usage of Codehaus Cargo with Payara Server as described in SERV-952.

2023-04-20 10:35 UTC, JamesHillyard requested changes
Is this actually enterprise only? I don't see why this wouldn't also work in Community

2023-04-20 10:35 UTC, JamesHillyard commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Extensions/Overview.adoc
> +xref:/Technical Documentation/Payara Server Documentation/Extensions/Codehaus Cargo/Overview.adoc[Codehaus Cargp]::
```suggestion
xref:/Technical Documentation/Payara Server Documentation/Extensions/Codehaus Cargo/Overview.adoc[Codehaus Cargo]::
```

2023-04-20 10:35 UTC, JamesHillyard commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Extensions/Codehaus Cargo/Overview.adoc
> +=== Remote deployment
```suggestion
[[remote-deployment]]
=== Remote Deployment
```

2023-04-20 10:35 UTC, JamesHillyard commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Extensions/Codehaus Cargo/Overview.adoc
> +=== Local deployment
```suggestion
[[local-deployment]]
=== Local Deployment
```

2023-04-20 10:35 UTC, JamesHillyard commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Extensions/Codehaus Cargo/Overview.adoc
> +=== Execution goals
```suggestion
=== Execution Goals
```

2023-04-20 10:35 UTC, JamesHillyard commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Extensions/Codehaus Cargo/Overview.adoc
> +== How to use it?
```suggestion
[[how-to-use-codehaus-cargo]]
== How to Use Codehaus Cargo
```

2023-04-20 10:35 UTC, JamesHillyard commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Extensions/Codehaus Cargo/Overview.adoc
> +== What can we do with it?
```suggestion
Codehaus Cargo allows you to::
```

2023-04-20 10:35 UTC, JamesHillyard commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Extensions/Codehaus Cargo/Overview.adoc
> +In the following table, you can find the list of the main goals provided by the Cargo plugin. For more information about the goals, please refer to the link:https://codehaus-cargo.github.io/cargo/Mav
This link is dead

2023-05-09 13:25 UTC, JamesHillyard approved these changes
This should still probably be available in the community docs (Unless I'm missing something?) - But the content looks good

2023-05-11 21:17 UTC, fturizo commented
@JamesHillyard  is correct, the documentation applies to both editions. I also moved the documentation to the Ecosystem section since it makes more sense to be there since the plugin is not an official extension of Payara Server.

2023-05-11 21:19 UTC, merged

2023-05-11 21:19 UTC, fturizo commented
@felixif, please make an equivalent PR for the Payara 6 branch.