FISH-6771: adding Netbeans transformer docs
payara/Payara-Documentation pull request #252
Opened 2023-04-20 04:24 UTC by breakponchito

Adding documentation for transformer integration with Netbeans

2023-04-20 10:58 UTC, JamesHillyard requested changes

2023-04-20 10:58 UTC, JamesHillyard commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +Apache NetBeans IDE provides tools to allow users to automatically convert the source code of Java/Jakarta EE 8 applications to Jakarta EE 10.
```suggestion
[[transform-to-jakartaee-10]]
= Transform Source Code to Jakarta EE 10

Apache NetBeans IDE provides tools to allow users to automatically convert the source code of Java/Jakarta EE 8 applications to Jakarta EE 10. 
```

2023-04-20 10:58 UTC, JamesHillyard commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +This will create a destination folder named *payara-sample* with the transformed file into it:
Does it always make a folder called 'payara-sample' or is because of the options you set? This is unclear from the images & test

2023-04-20 10:58 UTC, JamesHillyard commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +== Transform a Single File in the same Location
```suggestion
== Transform a Single File in the Same Location
```

2023-04-20 10:58 UTC, JamesHillyard commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +This will create a destination folder named *payara-sample* with the transformed folder and the contents into it:
Does it always make a folder called 'payara-sample' or is because of the options you set? This is unclear from the images & test

2023-04-20 10:58 UTC, JamesHillyard commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +== Transform all files in a Folder in the same Location
```suggestion
== Transform All Files in a Folder in the Same Location
```

2023-04-20 16:54 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +This will create a destination folder named *payara-sample* with the transformed folder and the contents into it:
yes that is needed in order to transform the file or folder to a different target folder. Internally I'm using a temporal pom to execute the transformer maven plugin, it is needed an available pom project to execute.

2023-04-20 16:56 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +Apache NetBeans IDE provides tools to allow users to automatically convert the source code of Java/Jakarta EE 8 applications to Jakarta EE 10.
Already done

2023-04-20 16:56 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +== Transform a Single File in the same Location
Already done

2023-04-20 16:56 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +== Transform all files in a Folder
Already done

2023-05-09 13:27 UTC, JamesHillyard approved these changes

2023-05-11 22:19 UTC, fturizo requested changes
In addition to my comments in the files, I noticed that the screen-shot for the code samples shows a lot of IDE errors in the Java code. Although this shouldn't be an issue from a feature perspective, I'd suggest reshooting the images without these errors and warnings to improve the presentation of the overall page.

2023-05-11 22:19 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +Check result of the transformation on the *Output* tab:
Read better as "Check the progress and result of the operation on the..."

2023-05-11 22:19 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +Once the file has been transformed, it will override the file. You can open with either Netbeans or a different editor:
Same comment as above

2023-05-11 22:19 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +Automatically Netbeans will open the project and you can verify results within the IDE:
Reads better as "NetBeans will automatically open the  new folder"

2023-05-23 00:20 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +Apache NetBeans IDE provides tools to allow users to automatically convert the source code of Java/Jakarta EE 8 applications to Jakarta EE 10.
this will be added as a new module into the netbeans, the release for this will be NB19

2023-05-23 03:24 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +To verify the resulting file you'll have to open it using either Netbeans or a different editor:
already done

2023-05-23 03:24 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +Check result of the transformation on the *Output* tab:
already done

2023-05-23 03:24 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +Once the file has been transformed, it will override the file. You can open with either Netbeans or a different editor:
already done

2023-05-23 03:24 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +Automatically Netbeans will open the project and you can verify results within the IDE:
already done

2023-05-25 21:14 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +Apache NetBeans IDE provides tools to allow users to automatically convert the source code of Java/Jakarta EE 8 applications to Jakarta EE 10.
Okay, in that case, please add an admonition stating which version of Apache Netbeans will have this feature included

2023-05-25 21:15 UTC, fturizo approved these changes
LGTM, just one final change required.

2023-05-26 00:07 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Jakarta EE10 Transformation.adoc
> +Apache NetBeans IDE provides tools to allow users to automatically convert the source code of Java/Jakarta EE 8 applications to Jakarta EE 10.
already added, thanks

2023-08-01 02:18 UTC, breakponchito commented
this was closed to change the base branch to payara6 on a different PR, here the new:  https://github.com/payara/Payara-Documentation/pull/293

2023-08-01 02:18 UTC, closed without merging