FISH-7522 Payara Community 6.2023.7 Release Notes and TCK Results
payara/Payara-Documentation pull request #284
Opened 2023-07-11 14:20 UTC by abdulrahim458

FISH-7522 Payara Community 6.2023.7 Release Notes and TCK Results

2023-07-11 15:29 UTC, JamesHillyard requested changes

2023-07-11 15:29 UTC, JamesHillyard commented on community/docs/modules/ROOT/pages/Eclipse MicroProfile Certification/6.2023.7/Overview.adoc
> +The following distributions of Payara 6.2023.6 are certified, with results for each listed below:
```suggestion
The following distributions of Payara 6.2023.7 are certified, with results for each listed below:
```

2023-07-11 15:29 UTC, JamesHillyard commented on community/docs/modules/ROOT/pages/Eclipse MicroProfile Certification/6.2023.7/Overview.adoc
> +* xref:Eclipse MicroProfile Certification/6.2023.6/Server TCK Results.adoc[Payara Server 6.2023.6]
```suggestion
* xref:Eclipse MicroProfile Certification/6.2023.7/Server TCK Results.adoc[Payara Server 6.2023.7]
```

2023-07-11 15:29 UTC, JamesHillyard commented on community/docs/modules/ROOT/pages/Eclipse MicroProfile Certification/6.2023.7/Overview.adoc
> +* xref:Eclipse MicroProfile Certification/6.2023.6/Server Web TCK Results.adoc[Payara Server 6.2023.6 - Web profile]
```suggestion
* xref:Eclipse MicroProfile Certification/6.2023.7/Server Web TCK Results.adoc[Payara Server 6.2023.7 - Web profile]
```

2023-07-11 15:29 UTC, JamesHillyard commented on community/docs/modules/ROOT/pages/Eclipse MicroProfile Certification/6.2023.7/Server TCK Results.adoc
> +https://docs.payara.fish/community/docs/6.2023.6/Eclipse%20MicroProfile%20Certification/6.2023.6/Server%20TCK%20Results.html
```suggestion
https://docs.payara.fish/community/docs/6.2023.7/Eclipse%20MicroProfile%20Certification/6.2023.7/Server%20TCK%20Results.html
```

2023-07-11 15:29 UTC, JamesHillyard commented on community/docs/modules/ROOT/pages/Release Notes/Release Notes 6.2023.7.adoc
> +* [https://github.com/payara/Payara/pull/6292[FISH-1419]] [Community Contribution - https://github.com/lprimak[Iprimak]] Hazelcast Partition Group according to Instance Group
```suggestion
* [https://github.com/payara/Payara/pull/6292[FISH-1419]] [Community Contribution - https://github.com/lprimak[lprimak]] Hazelcast Partition Group according to Instance Group
```

2023-07-11 18:21 UTC, abdulrahim458 commented on community/docs/modules/ROOT/pages/Eclipse MicroProfile Certification/6.2023.7/Overview.adoc
> +The following distributions of Payara 6.2023.6 are certified, with results for each listed below:
Corrected the version

2023-07-11 18:21 UTC, abdulrahim458 commented on community/docs/modules/ROOT/pages/Eclipse MicroProfile Certification/6.2023.7/Overview.adoc
> +* xref:Eclipse MicroProfile Certification/6.2023.6/Server TCK Results.adoc[Payara Server 6.2023.6]
Corrected the version

2023-07-11 18:22 UTC, abdulrahim458 commented on community/docs/modules/ROOT/pages/Eclipse MicroProfile Certification/6.2023.7/Server TCK Results.adoc
> +https://www.payara.fish/downloads/payara-platform-community-edition/[Payara Server 6.2023.6]
Corrected the version

2023-07-11 18:22 UTC, abdulrahim458 commented on community/docs/modules/ROOT/pages/Release Notes/Release Notes 6.2023.7.adoc
> +* [https://github.com/payara/Payara/pull/6292[FISH-1419]] [Community Contribution - https://github.com/lprimak[Iprimak]] Hazelcast Partition Group according to Instance Group
Corrected the url

2023-07-11 18:22 UTC, abdulrahim458 commented on community/docs/modules/ROOT/pages/Eclipse MicroProfile Certification/6.2023.7/Server TCK Results.adoc
> +**Payara Server 6.2023.6 Full Profile Certification Summary**
Corrected the version

2023-07-12 09:21 UTC, JamesHillyard approved these changes

2023-07-12 09:22 UTC, merged