FISH-7520 Payara Enterprise 5.53.0 Release Notes and TCK Results
payara/Payara-Documentation pull request #285
Opened 2023-07-11 15:06 UTC by abdulrahim458

FISH-7520 Payara Enterprise 5.53.0 Release Notes and TCK Results

2023-07-11 15:33 UTC, JamesHillyard requested changes

2023-07-11 15:33 UTC, JamesHillyard commented on enterprise/docs/modules/ROOT/pages/Release Notes/Release Notes 5.53.0.adoc
> +* [FISH-6291 ]Data synchronization issue in a @Clustered @Singleton
```suggestion
* [FISH-6291] Data synchronization issue in a @Clustered @Singleton
```

2023-07-11 18:31 UTC, abdulrahim458 commented on enterprise/docs/modules/ROOT/pages/Release Notes/Release Notes 5.53.0.adoc
> +* [FISH-6291 ]Data synchronization issue in a @Clustered @Singleton
Corrected spaces

2023-07-12 09:21 UTC, JamesHillyard approved these changes

2023-07-12 09:22 UTC, merged