Fish 7479 create advisor tool documentation
payara/Payara-Documentation pull request #292
Opened 2023-07-27 03:53 UTC by breakponchito

Adding Upgrade Advisor Tool Documentation

2023-07-28 15:12 UTC, Pandrex247 requested changes
Some suggestions and fixes

2023-07-29 00:30 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Advisor Tool.adoc
> +This is a CLI (Command Line Interface) tool to advise changes added in Jakarta 10 that affect applications based on Jakarta 8 or 9. The idea of the tool is to summarize all changes that affect your a
already done

2023-07-29 00:30 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Advisor Tool.adoc
> +IMPORTANT: Something important to note is that not all the specs add changes between versions, that is why for the current version some specs won’t show any advises for the implementation code.
already removed, thanks

2023-07-29 00:30 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Advisor Tool.adoc
> +[[hot-to-use]]
fixed

2023-07-29 00:30 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Advisor Tool.adoc
> +You can use directly from command line without configuring anything on your local environment. This is resolved by maven central because this tool was uploaded under the following link: https://mvnre
already done

2023-07-29 00:31 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Advisor Tool.adoc
> +|Message to indicate what is the recommended way to proceed with the advisory to make the application compatible with Jakarta 10
yeah that is good point, I changed a little to explain the structure of each line and then the description of each part

2023-07-29 00:31 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Advisor Tool.adoc
> +IMPORTANT: The log messages for the advisors are (ASCII) colour-coded to make the user more apprehensive about what they need to change.
already removed

2023-07-29 00:31 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Advisor Tool.adoc
> +The following are examples of each of the available types of advisors with the different colors in their structure.
already done

2023-07-29 00:31 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Advisor Tool.adoc
> +For Jakarta 10 the property nillable was marked as deprecated, as a modification for Jakarta JSON Binding 3.0, you can check here: https://jakarta.ee/specifications/jsonb/3.0/[Jakarta JSON Binding 3.
already done

2023-07-29 00:32 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Advisor Tool.adoc
> +Now with the use of the Upgrade Advisor Tool we can get the advise related to this change as follows:
already done

2023-07-29 00:32 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Advisor Tool.adoc
> +From the message we can see that the recommendation is to start to use the new annotation JsonbNillable. Then we can have the following code by applying the advise from the tool:
already done

2023-07-29 00:32 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Advisor Tool.adoc
> +As as conclusion this tool will help us to make our old Jakarta 8/9 applications compatible with last changes added in Jakarta 10.
already done

2023-07-31 09:08 UTC, Pandrex247 requested changes

2023-07-31 09:08 UTC, Pandrex247 commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Advisor Tool.adoc
> +IMPORTANT: The log messages for the advisors are (ASCII) colour-coded to make the user more apprehensive about what they need to change.
Not sure you did?

2023-08-01 02:16 UTC, closed without merging

2023-08-01 02:16 UTC, breakponchito commented
this was closed to change the base branch on a different PR, here the new: https://github.com/payara/Payara-Documentation/pull/294