FISH-7645 Documentation for Docker and WSL support in IDEs
payara/Payara-Documentation pull request #303
Opened 2023-08-24 03:22 UTC by jGauravGupta

2023-09-01 10:49 UTC, JamesHillyard requested changes

2023-09-01 10:49 UTC, JamesHillyard commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/Eclipse Plugin/Payara Server.adoc
> +`docker run -p 8080:8080 -p 4848:4848 -p 9009:9009 -v HOST_PATH:CONTAINER_PATH  payara/server-full:latest`
The latest image would be Payara 6. This should be 5.2022.5 or use `{page-version}`

2023-09-01 10:49 UTC, JamesHillyard commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Payara Server.adoc
> +`docker run -p 8080:8080 -p 4848:4848 -p 9009:9009 -v HOST_PATH:CONTAINER_PATH  payara/server-full:latest`
The latest image would be Payara 6. This should be 5.2022.5 or use {page-version}

2023-09-01 10:49 UTC, JamesHillyard commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/IDE Integration/VSCode Extension/Payara Server.adoc
> +`docker run -p 8080:8080 -p 4848:4848 -p 9009:9009 -v HOST_PATH:CONTAINER_PATH  payara/server-full:latest`
The latest image would be Payara 6. This should be 5.2022.5 or use {page-version}

2023-09-13 22:03 UTC, fturizo approved these changes
I made some layout changes to keep the style consistent. Good work!

2023-09-13 22:05 UTC, merged