FISH-8109 Extending Amazon SQS Connector with methods from AWS SqsClient class
payara/Payara-Documentation pull request #405
Opened 2024-02-26 06:56 UTC by jGauravGupta

2024-03-07 22:47 UTC, fturizo requested changes
Needs a rewrite, see comments.

2024-03-07 22:47 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS/Queue Management.adoc
> +[[managing-queues]]
I don't think that this section offers clarity on what the feature that the connector offers is. The customer's original request was for a way to programmatically manage queues and other Sqs resources using the SqsClient API, correct? 

Instead of stating how to manage queues using the API and giving examples, it is better to just teach the user on how to access the API programmatically by getting the connection factory like this:

   @Resource(lookup = "java:app/amazonsqs/factory")
    private AmazonSQSConnectionFactory factory;

And then showing examples of how to create connections to interact with SQS resources. Linking to the official  AWS SQS documentation should be enough too

Also, I'm confused about something: Where is the `SQSClient` class being used here? The examples listed use specific classes whereas in the JIRA issue, the API used corresponds to this class.

Finally, shouldn't instructions on how to add the Maven dependencies for these classes be added as well?

2024-03-09 15:51 UTC, jGauravGupta commented on docs/modules/ROOT/pages/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS/Queue Management.adoc
> +[[managing-queues]]
Thanks for the feedback; I'll review and make the necessary improvements.

> The customer's original request was for a way to programmatically manage queues and other Sqs resources using the SqsClient API, correct?

Yes.

> Also, I'm confused about something: Where is the SQSClient class being used here?

The customer has not requested to expose the SqsClient API directly. However, to manage queues programmatically, it is implemented as a wrapper in AmazonSQSConnection.

> Finally, shouldn't instructions on how to add the Maven dependencies for these classes be added as well?

No extra Maven dependency is needed; it should be as defined in the Overview page.

2024-03-12 22:15 UTC, fturizo approved these changes
Improved code snippets and re-worded section structure.

2024-03-12 22:15 UTC, merged