FISH-8387 Diagnostics Tool documentation
payara/Payara-Documentation pull request #422
Opened 2024-03-29 11:31 UTC by kalinchan

2024-04-04 15:49 UTC, Pandrex247 requested changes

2024-04-04 15:49 UTC, Pandrex247 commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Configuration Options/Diagnostics Tool.adoc
> +Diagnostics can be collected directly from an instance when the DAS is not accessible by specifying the Asadmin port.
```suggestion
Diagnostics can be collected directly from an instance if not local to the DAS by specifying the admin port of the target instance.
```

2024-04-05 23:01 UTC, fturizo requested changes
On top of the changes I suggested, this page needs additional changes:

* The location of this page is not correct, as this feature doesn't pertain to server configuration. This page should go into a new section Technical Documentation --> Payara Server Documentation --> Diagnostics and Troubleshooting
* The documentation should give more information about the structure of the ZIP bundle created by the `collect-diagnostics` command and should provide an example of the command output for better clarity.

2024-05-24 20:45 UTC, fturizo commented
@kalinchan, I have brought over the changes of this PR on a new one that targets the `main-5` #435 as the `master` branch is not to be used anymore. I have also made some adjustments to the page structure and improved its readability. 

Additionally, I have created a Payara Platform 6.x counterpart and updated the documentation under the new revamped structure in #436, make sure to give it a look if you have the chance.

2024-05-24 20:45 UTC, closed without merging