FISH-8260 Document Evaluation of Extra Params in OpenID
payara/Payara-Documentation pull request #444
Opened 2024-06-19 15:09 UTC by aubi

Documentation of change in 
https://github.com/payara/ecosystem-security-connectors/pull/348

2024-06-20 19:38 UTC, fturizo requested changes
Needs some clarification on the changes made, see my comments. Also, @aubi, does this change only apply to Payara Plat 5, or does this PR need an equivalent one for 6.x?

2024-06-20 19:38 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Public API/OpenID Connect Support.adoc
> +| `payara.security.openid.extraParams.raw` (compatibility with older version)
What does the `compatibility with older version` sentence mean? Is this property new to `5.65.0` or is it the other way around?

2024-06-20 19:38 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Public API/OpenID Connect Support.adoc
> +| The content is supposed to be an EL expression. The expression must evaluate as either list of strings (apply the same rules as for `extraParameters`) or a string - this is split by comma and the s
Remove the ambiguity, instead of saying "The content is supposed to be an EL expression", state: "Corresponds to an EL expression string", for example.
Also, put the example on a new line to improve the cell's readability.

2024-06-20 19:38 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Public API/OpenID Connect Support.adoc
> +The `extraParameters` option is syntactically an array of strings, so it cannot be directly injected by MP Config, which can only provide strings. There are ways, how to configure it:
I'm a bit confused by this section and the change implemented, I have some questions:

. Isn't injecting a list/array of strings through MP Configuration technically possible? I recall that you can do this by using a custom converter. 
. Was the change implemented to the `payara.security.openid.extraParams` property? Did it support MP config injection before and now the `payara.security.openid.extraParams.raw` property supports it?

2024-06-20 19:38 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Public API/OpenID Connect Support.adoc
> +2. Expression-Based Configuration: The `extraParametersExpression` option was introduced for configuring arrays in a manner similar to Jakarta 10 and later. This option is evaluated as an EL expressi
Remember that this is the Payara Plat 5.x documentation, so mentioning Jakarta EE 10 here doesn't make much sense. I would remove this sentence.

2024-06-20 19:38 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Public API/OpenID Connect Support.adoc
> +
I'd add an example or 2 to clarify how these properties are expected to work in different scenarios since it is a bit confusing.

2024-06-21 08:23 UTC, aubi commented on docs/modules/ROOT/pages/Technical Documentation/Public API/OpenID Connect Support.adoc
> +| `payara.security.openid.extraParams.raw` (compatibility with older version)
`payara.security.openid.extraParams.raw` is an older feature, for some reason not properly documented. The `extraParamsProperties` is a better solution, backported from similar annotation in Jakarta EE 10.

E.g. it is backported only to Payara 5, as Payara 6 (Jakarta EE 10) has the Jakarta annotation and there is no need for Payara-specific version.

2024-07-01 14:20 UTC, aubi commented on docs/modules/ROOT/pages/Technical Documentation/Public API/OpenID Connect Support.adoc
> +2. Expression-Based Configuration: The `extraParametersExpression` option was introduced for configuring arrays in a manner similar to Jakarta 10 and later. This option is evaluated as an EL expressi
The request from the customer was "Do it similarly to JEE 10", so I thought it would be good to mention it here. I could use a work "backport".

2024-07-04 08:21 UTC, Pandrex247 commented on docs/modules/ROOT/pages/Technical Documentation/Public API/OpenID Connect Support.adoc
> +The `extraParametersExpression` option was introduced in a manner similar to Jakarta 10 and later. If specified, this option is evaluated as an EL expression, e.g. it expects a bean returning the con
The product is Jakarta EE 10, not Jakarta 10
```suggestion
The `extraParametersExpression` option was introduced in a manner similar to Jakarta EE 10 and later. If specified, this option is evaluated as an EL expression, e.g. it expects a bean returning the configuration. If it returns a list of strings, these strings are used in the form `"key=value"`. Values can use further expressions to be configurable at runtime.
```

2024-07-04 15:01 UTC, aubi commented on docs/modules/ROOT/pages/Technical Documentation/Public API/OpenID Connect Support.adoc
> +The `extraParametersExpression` option was introduced in a manner similar to Jakarta 10 and later. If specified, this option is evaluated as an EL expression, e.g. it expects a bean returning the con
FISH-8260 jakarta "EE" forgotten

2024-07-05 09:10 UTC, Pandrex247 commented on docs/modules/ROOT/pages/Technical Documentation/Public API/OpenID Connect Support.adoc
> +| Overrides `extraParameters`, if specified, `extraParameters` is ignored. An array of extra options to be sent to the OpenID Connect provider.
I'd reword this.
```suggestion
| An array of extra options to be sent to the OpenID Connect provider in the form of an Expression Language expression. If specified, overrides `extraParameters`. 
```

2024-07-05 09:10 UTC, Pandrex247 commented on docs/modules/ROOT/pages/Technical Documentation/Public API/OpenID Connect Support.adoc
> +The annotation supports the MP Config value `payara.security.openid.extraParams.raw` (see `OpenIdAuthenticationDefinition.OPENID_MP_EXTRA_PARAMS_RAW`) in form of URL-encoded parameters. If specified,
> If specified, it takes precedence

Over what? The text in the configuration options table would indicate that `extraParametersExpression` takes precedence over this `extraParameters`.

I think this needs clarifying

2024-07-05 10:29 UTC, Pandrex247 commented on docs/modules/ROOT/pages/Technical Documentation/Public API/OpenID Connect Support.adoc
> +| An array of extra options to be sent to the OpenID Connect provider in the form of an Expression Language expression. If specified, overrides `extraParameters`.
```suggestion
| An array of extra options to be sent to the OpenID Connect provider in the form of an Expression Language expression. If specified, overrides `extraParameters` (but not `payara.security.openid.extraParams.raw`). 
```

2024-07-05 10:29 UTC, Pandrex247 commented on docs/modules/ROOT/pages/Technical Documentation/Public API/OpenID Connect Support.adoc
> +There are several ways, how to configure `extraParameters` using Expression Language and Microprofile Config.
```suggestion
There are several ways, how to configure `extraParameters` using Expression Language and MicroProfile Config. The order of precedence is: `payara.security.openid.extraParams.raw` overrides `extraParametersExpression`, which overrides the plain `extraParams` value.
```

2024-07-05 13:48 UTC, Pandrex247 approved these changes

2024-07-05 23:34 UTC, fturizo approved these changes
Improved the wording and structured based on your examples, @aubi.

2024-07-05 23:34 UTC, merged