SERV-804 Document Payara Embedded & Its JDK 17 Considerations
payara/Payara-Documentation pull request #47
Opened 2022-07-19 12:45 UTC by JamesHillyard

Documents the JDK 17 Considerations for Payara Embedded. Currently there is no documentation page dedicated to Payara Embedded so I had to document that too.

2022-07-20 20:43 UTC, fturizo requested changes
Looks really good. Some changes are needed. Additionally added some fixes for the source blocks to correctly resolve page attributes.

2022-07-20 20:43 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Payara Server Embedded.adoc
> +Payara Embedded has two distributions, `payara-embedded-all` and `payara-embedded-web`, functionally these are the same as their standalone counterparts, Payara Server and Payara Server Web respectiv
I'd say "has 2 distribution variants", since Embedded is the actual distribution

2022-07-20 20:43 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Payara Server Embedded.adoc
> +Payara Embedded has two distributions, `payara-embedded-all` and `payara-embedded-web`, functionally these are the same as their standalone counterparts, Payara Server and Payara Server Web respectiv
Also, the distinction  is between "Payara Server Full Profile" and "Payara Server Web Profile"

2022-07-20 20:43 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Payara Server Embedded.adoc
> + * @author James Hillyard <james.hillyard@payara.fish>
Make sure not to include any personal details.

2022-07-20 20:43 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Payara Server Embedded.adoc
> +TIP: Unless you require specifications only in the Jakarta Full Profile, like SOAP support, you should use Payara Micro instead.
The phrasing of this tip is a bit confusing. Do you mean that users should use Payara Micro if they want to use vanilla Jakarta EE? In that case, this may read better: 

"For deploying standard Jakarta EE applications, in most cases you should use Payara Micro instead".

2022-07-20 20:43 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Payara Server Embedded.adoc
> +Starting Payara Embedded for testing can also be done using the Arquillian connector. In that case, the setup and teardown of Payara is managed for you. Read about the xref:Technical Documentation/Ec
The Arquillian connector link would look better in a "See Also" section.

2022-07-21 09:57 UTC, JamesHillyard commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Payara Server Embedded.adoc
> +TIP: Unless you require specifications only in the Jakarta Full Profile, like SOAP support, you should use Payara Micro instead.
I'm trying to say you should use Payara Micro instead of Embedded in this case unless you require Jakarta EE Full Profile features like SOAP, as Payara Micro is based on the Web profile and therefore doesn't support those features

2022-07-21 19:57 UTC, fturizo approved these changes
Changes looks good

2022-07-21 19:59 UTC, fturizo commented
Also, this PR should go to the 39.0 and 40.0 branches as well.

2022-07-21 21:10 UTC, merged

2022-07-21 21:13 UTC, JamesHillyard commented
> Also, this PR should go to the 39.0 and 40.0 branches as well.

SERV-811 will put this in the 39.0, 40.0 and 41.0 branches