FISH-9690: adding documentation for new grizzly properties to protect from RFC-9110 invalid characters
payara/Payara-Documentation pull request #509
Opened 2024-11-14 05:41 UTC by breakponchito

this is documentation for new properties added on the grizzly implementation to protect against RFC-9110 invalid characters on the Http Header Name and Http Header Validation

2024-12-09 10:13 UTC, Pandrex247 commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/General Administration/Administering HTTP Connectivity.adoc
> +The following sections will describe how to configure the new options from grizzly.
```suggestion
The following sections will describe how to configure the new options from Grizzly.
```

2024-12-09 10:40 UTC, Pandrex247 commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/General Administration/Administering HTTP Connectivity.adoc
> +|This property enable the validation of the Header Name content to prevent any usage of invalid characters on it. By default, this property is set as false on the grizzly implementation. You need to
```suggestion
|This property enable the validation of the Header Name content to prevent any usage of invalid characters on it. By default, this property is set as false on the Grizzly implementation. You need to set as true to enable HTTP Header Name content validation
```

2024-12-13 21:44 UTC, fturizo requested changes

2024-12-13 21:44 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/General Administration/Administering HTTP Connectivity.adoc
> +IMPORTANT: Currently there is a reported CVE with number  https://www.cve.org/CVERecord?id=CVE-2024-45687[CVE-2024-45687] that indicates a risk when not protecting against invalid characters on the H
I'd remove this warning, as the user doesn't need to know about this particular CVE. They should know that the validation is in place as a generic security measure since the use of the mentioned characters is dangerous.

2024-12-13 21:44 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/General Administration/Administering HTTP Connectivity.adoc
> +----
I'd remove this section, there's no need to teach the user to enable/disable this validation

2024-12-13 21:44 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/General Administration/Administering HTTP Connectivity.adoc
> +----
Same comment as above, no need to teach this to the user.

2024-12-13 21:44 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/General Administration/Administering HTTP Connectivity.adoc
> +NOTE: In the case of HTTP Header Value validation this is less restrict than Header Name validation because it is possible to send multiple \n. This will cause to include new line on the value conten
This is no longer true, the RFC is clear that the `LF` character is also NOT allowed on values.

2024-12-16 22:46 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/General Administration/Administering HTTP Connectivity.adoc
> +The following options can help you to protect against invalid characters on the HTTP Header Name and HTTP Header Value content. You can follow the RFC-9110 documentation (See section 5.5 of: https://
already done

2024-12-16 22:46 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/General Administration/Administering HTTP Connectivity.adoc
> +|This property enable the validation of the Header Name content to prevent any usage of invalid characters on it. By default, this property is set as false on the grizzly implementation. You need to
already done

2024-12-16 22:46 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/General Administration/Administering HTTP Connectivity.adoc
> +----
already done

2024-12-16 22:46 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/General Administration/Administering HTTP Connectivity.adoc
> +NOTE: In the case of HTTP Header Value validation this is less restrict than Header Name validation because it is possible to send multiple \n. This will cause to include new line on the value conten
already done

2024-12-16 22:46 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/General Administration/Administering HTTP Connectivity.adoc
> +IMPORTANT: Currently there is a reported CVE with number  https://www.cve.org/CVERecord?id=CVE-2024-45687[CVE-2024-45687] that indicates a risk when not protecting against invalid characters on the H
already done

2024-12-16 22:47 UTC, breakponchito commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/General Administration/Administering HTTP Connectivity.adoc
> +The following sections will describe how to configure the new options from grizzly.
already done

2024-12-16 22:53 UTC, breakponchito commented
@fturizo fixes applied to the documentation

2025-01-02 19:30 UTC, fturizo approved these changes
Did some rewriting as the intent wasn't fully clear now that the validation behaviour is turned on by default.

2025-01-02 19:33 UTC, merged