FISH-5980 Concurrency Documentation
payara/Payara-Documentation pull request #52
Opened 2022-08-02 22:55 UTC by luiseufrasio

2022-08-03 08:04 UTC, AlanRoth commented
Can you run generate-nav.py to update the Antora nav? You can find more info here; [Generate Nav Script](https://payara.atlassian.net/wiki/spaces/SUP/pages/2904784897/Generate+Nav+Script)

2022-08-03 09:05 UTC, JamesHillyard commented
@luiseufrasio Just checking before I review - is this documentation for Payara 5, Payara 6 or both? If both, does the same documentation apply for both versions?

2022-08-03 20:49 UTC, fturizo requested changes
Looks good, but certain structural changes are needed. Check my comments.

2022-08-03 20:49 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/About Concurrent Resources.adoc
> += About Concurrent Resources
I agree with this comment as well, both pages should be combined into one.

2022-08-03 20:49 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/About Concurrent Resources.adoc
> +For detailed information about concurrent resources, see "Concurrency Utilities" in The Java EE 8 Tutorial. Also see Java Specification Request 236: Concurrency Utilities for Java EE (http://jcp.org/
I think that this section can be removed from the page since the main premise of Payara's documentation is that it's complementary to the existing Java/ Jakarta EE specifications. Also, the link shared is outdated since all of the specs now reside on the Eclipse Foundation websites.

2022-08-03 20:49 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Overview.adoc
> +Payara Server provides procedures for administering concurrent resources by using the asadmin command-line utility.
this sentence should read: "using the Asadmin CLI and the Admin console" since these changes can be done from the admin console as stated below.

2022-08-03 20:49 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Overview.adoc
> +xref:/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Default Concurrent Resources.adoc[Default Concurrent Resources]:: The Java EE st
Instead of "Jakarta EE standard", correctly state "Jakarta Concurrency specification"

2022-08-03 20:49 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Configuring Context Services.adoc
> +* xref:#to-create-context-service[To Create a Context Service]
There's no need to create a list of internal references to the contents of the page since this is done automatically by Antora, so this list of links can be removed.

2022-08-03 20:49 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Configuring Context Services.adoc
> +=== See Also
Instead of a "See Also" sub-section in each CRUD action, a simple TIP admonition is better and improves readability.

2022-08-03 20:49 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Configuring Managed Executor Services.adoc
> +* xref:#to-create-managed-executor-service[To Create a Managed Executor Service]
There's no need to create a list of internal references to the contents of the page since this is done automatically by Antora, so this list of links can be removed.

2022-08-03 20:49 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Configuring Context Services.adoc
> +* xref:#to-create-context-service[To Create a Context Service]
This applies to the other pages as well.

2022-08-03 20:49 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Configuring Managed Scheduled Executor Services.adoc
> +* xref:#to-create-managed-scheduled-executor-service[To Create a Managed Scheduled Executor Service]
There's no need to create a list of internal references to the contents of the page since this is done automatically by Antora, so this list of links can be removed.

2022-08-03 20:49 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Configuring Managed Thread Factories.adoc
> +* xref:#to-create-managed-thread-factory[To Create a Managed Thread Factory]
There's no need to create a list of internal references to the contents of the page since this is done automatically by Antora, so this list of links can be removed.

2022-08-03 20:49 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Default Concurrent Resources.adoc
> +The Java EE standard specifies that certain default resources be made available to applications, and defines specific JNDI names for these default resources. GlassFish Server makes these names availa
Instead of "Java EE standard", it should read as "Jakarta EE specification"

2022-08-03 20:49 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Default Concurrent Resources.adoc
> +*java:comp/DefaultContextService* +
Resource names and their mappings should be under monospaced format like this: `java:comp/DefaultContextService` - `concurrent/__defaultContextService`

2022-08-03 20:49 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Default Concurrent Resources.adoc
> +This Java EE standard name is mapped to the concurrent/__defaultContextService resource.
Weirdly phrased. Might read better as "Jakarta Concurrency standard name mapped to the..."

2022-08-03 20:49 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Using Admin Console.adoc
> +[[using-admin-console]]
Agree with James' comments since this page mixes instructions on how to manage resources using the Admin console and using Asadmin CLI commands that have been described on other pages.

2022-08-03 21:45 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/About Concurrent Resources.adoc
> +For detailed information about concurrent resources, see "Concurrency Utilities" in The Java EE 8 Tutorial. Also see Java Specification Request 236: Concurrency Utilities for Java EE (http://jcp.org/
Done!

2022-08-03 22:11 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/About Concurrent Resources.adoc
> += About Concurrent Resources
done!

2022-08-03 22:11 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Default Concurrent Resources.adoc
> += Default Concurrent Resources
done!

2022-08-03 22:14 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Overview.adoc
> +Payara Server provides procedures for administering concurrent resources by using the asadmin command-line utility.
done!

2022-08-03 22:16 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Overview.adoc
> +xref:/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Default Concurrent Resources.adoc[Default Concurrent Resources]:: The Java EE st
it was removed/moved

2022-08-04 11:36 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Configuring Context Services.adoc
> +* xref:#to-create-context-service[To Create a Context Service]
done!

2022-08-04 11:36 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Configuring Managed Thread Factories.adoc
> +* xref:#to-create-managed-thread-factory[To Create a Managed Thread Factory]
done!

2022-08-04 11:46 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Default Concurrent Resources.adoc
> +*java:comp/DefaultContextService* +
done!

2022-08-04 11:53 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Default Concurrent Resources.adoc
> +This Java EE standard name is mapped to the concurrent/__defaultContextService resource.
done

2022-08-04 12:30 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Using Admin Console.adoc
> +[[using-admin-console]]
done!

2022-08-06 11:17 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Default Concurrent Resources.adoc
> +The Java EE standard specifies that certain default resources be made available to applications, and defines specific JNDI names for these default resources. GlassFish Server makes these names availa
done!

2022-08-06 11:18 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Configuring Managed Executor Services.adoc
> +* xref:#to-create-managed-executor-service[To Create a Managed Executor Service]
removed

2022-08-06 11:18 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Configuring Managed Scheduled Executor Services.adoc
> +* xref:#to-create-managed-scheduled-executor-service[To Create a Managed Scheduled Executor Service]
removed

2022-08-06 11:18 UTC, luiseufrasio commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Configuring Context Services.adoc
> +=== See Also
"See also" removed

2022-08-08 11:05 UTC, AlanRoth approved these changes

2022-08-08 12:33 UTC, JamesHillyard commented
@luiseufrasio instead of making lots of small recommendations, I have just added them in the latest commit, please review those changes, contact me for any questions or changes you think are incorrect.

2022-08-09 11:11 UTC, luiseufrasio reviewed
LGTM!

2022-08-09 11:12 UTC, JamesHillyard approved these changes

2022-08-09 11:12 UTC, JamesHillyard commented
@fturizo Can you re-review so this PR can be merged please?

2022-08-10 19:58 UTC, fturizo approved these changes
Changes look good, did some small adjustments, can proceed to merge

2022-08-11 11:29 UTC, merged

2022-08-11 13:23 UTC, JamesHillyard commented
We never updated the Nav 🤦 See the above PR.