FISH-6298 Yaml result added with the explanation about 'endpoints'
payara/Payara-Documentation pull request #53
Opened 2022-08-03 16:18 UTC by luiseufrasio

2022-08-03 20:58 UTC, fturizo requested changes
Some changes needed to improve consistency of the documented change.

2022-08-03 20:58 UTC, fturizo commented on community/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc
> +*yaml Result [http://localhost:8080/openapi]*::
Might be good to add a "Here's an example of how the OpenAPI document of a sample application would look like:"

2022-08-03 20:58 UTC, fturizo commented on community/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc
> +IMPORTANT: The item `endpoints` is a Payara extension from the Specification. It was created to expose the endpoints for each application deployed.
I think this is an odd way to explain what multiple endpoints would look like. I have 2 suggestions to improve this feature:

1. Instead of an admonition, add a new section called "Deployed endpoints", where you can explain that the `endpoints` attribute in the document is a Payara Platform-specific extension that lists all deployed endpoints.
2. Present a short example of how the OpenAPI document would look like when there are 2 applications that have OpenAPI definitions deployed in a server instance. This would help the user understand better how the endpoints attribute works.

2022-08-03 20:58 UTC, fturizo commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc
> +*yaml Result [http://localhost:8080/openapi]*::
Same comments as above.

2022-08-06 12:51 UTC, luiseufrasio commented on community/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc
> +IMPORTANT: The item `endpoints` is a Payara extension from the Specification. It was created to expose the endpoints for each application deployed.
done!

2022-08-06 12:53 UTC, luiseufrasio commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc
> +*yaml Result [http://localhost:8080/openapi]*::
done

2022-08-06 12:53 UTC, luiseufrasio commented on community/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc
> +*yaml Result [http://localhost:8080/openapi]*::
done

2022-08-08 08:28 UTC, AlanRoth commented on community/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc
> +In case we have more than one application deployed, a merge is done in openapi document. The resultant document has all applications and paths. In order to make the document more legible, the attribu
```suggestion
In case we have more than one application deployed, a merge is done in the OpenAPI document. The resultant document has all applications and paths. In order to make the document more legible, the attribute `endpoints` was added as a Payara Platform specific extension which lists all deployed endpoints grouped by the application context root.
```

2022-08-08 08:28 UTC, AlanRoth commented on enterprise/docs/modules/ROOT/pages/Technical Documentation/MicroProfile/OpenAPI.adoc
> +In case we have more than one application deployed, a merge is done in openapi document. The resultant document has all applications and paths. In order to make the document more legible, the attribu
```suggestion
In case we have more than one application deployed, a merge is done in the OpenAPI document. The resultant document has all applications and paths. In order to make the document more legible, the attribute `endpoints` was added as a Payara Platform specific extension which lists all deployed endpoints grouped by the application context root.
```

2022-08-09 11:09 UTC, AlanRoth approved these changes

2022-08-09 22:35 UTC, fturizo approved these changes

2022-08-09 22:35 UTC, fturizo commented
Added some small adjustments to the wording, looks good.

2022-08-09 22:35 UTC, merged