FISH-6460 Add release notes and tck results 5.42.0
payara/Payara-Documentation pull request #54
Opened 2022-08-05 13:31 UTC by kalinchan

2022-08-05 14:32 UTC, JamesHillyard requested changes
~Can you run generate-nav.py to update the Antora nav? You can find more info here; [Generate Nav Script](https://payara.atlassian.net/wiki/spaces/SUP/pages/2904784897/Generate+Nav+Script)~

2022-08-05 14:32 UTC, JamesHillyard commented on enterprise/docs/modules/ROOT/pages/Release Notes/Release Notes 5.42.0.adoc
> +# Release notes - Payara Platform Enterprise 5.42
```suggestion
# Release notes - Payara Platform Enterprise 5.42.0

```

2022-08-08 11:07 UTC, AlanRoth commented on enterprise/docs/modules/ROOT/pages/Release Notes/Release Notes 5.42.0.adoc
> +# Release notes - Payara Platform Enterprise 5.42
I believe Kalin's changes are only to the Partial files which are excluded from the script (this is by design)

2022-08-08 11:18 UTC, JamesHillyard approved these changes

2022-08-08 11:28 UTC, merged