FISH-6460 Update release notes and security fix list
payara/Payara-Documentation pull request #61
Opened 2022-08-10 09:36 UTC by kalinchan

2022-08-10 09:40 UTC, JamesHillyard commented
Do we want a note about this like we did with the [5.31.0 release](https://docs.payara.fish/enterprise/docs/Release%20Notes/Release%20Notes%205.31.0.html )? CC @Pandrex247

2022-08-10 09:42 UTC, Pandrex247 requested changes
You may as well update the security fix list for Community while you're at it.

2022-08-10 09:43 UTC, Pandrex247 commented
> Do we want a note about this like we did with the [5.31.0 release](https://docs.payara.fish/enterprise/docs/Release%20Notes/Release%20Notes%205.31.0.html)? CC @Pandrex247

Wouldn't go amiss IMO but I'm not the documentation master and not up-to-date with how we're styling things now during Documentation 1.5 / 2.0

2022-08-10 09:51 UTC, JamesHillyard commented
> > Do we want a note about this like we did with the [5.31.0 release](https://docs.payara.fish/enterprise/docs/Release%20Notes/Release%20Notes%205.31.0.html)? CC @Pandrex247
> 
> Wouldn't go amiss IMO but I'm not the documentation master and not up-to-date with how we're styling things now during Documentation 1.5 / 2.0

Note added

2022-08-10 09:55 UTC, JamesHillyard commented on community/docs/modules/ROOT/pages/Security/Security Fix List.adoc
> +|https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-37422[CVE-2022-37422] | N/A | FIXED | Vulnerability exploit using ROOT context root deployments | 5.2022.2 | https://github.com/payara/Payara/
```suggestion
|https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-37422[CVE-2022-37422] | N/A | FIXED | Vulnerability exploit using ROOT context root deployments | 5.2022.3 | https://github.com/payara/Payara/pull/5886[#5886] | Recommended to immediately upgrade to this release if any of your applications is deployed on the / context root on Payara Server or Payara Micro
```

2022-08-10 10:10 UTC, JamesHillyard approved these changes

2022-08-10 14:28 UTC, AlanRoth approved these changes

2022-08-11 08:15 UTC, JamesHillyard commented
@Pandrex247 could you re-review this so it can be merged please?

2022-08-11 08:34 UTC, Pandrex247 approved these changes

2022-08-11 09:01 UTC, merged